on:
  pull_request:
    types: [opened, reopened]
    branches:
    - main
    - develop
jobs:
  ding_talk_notify:
    runs-on: ubuntu-latest
    steps:
    - name: DingTalkNotify
      uses: wow-actions/dingtalk-notify@v1.1.0
      with:
        # Dingtalk bot token
        token: ${{ secrets.DINGTALK_SECRET }}
        # The secret to sign the request
        secret: ${{ secrets.DINGTALK_TOKEN }}
        # Dingtalk message type. Valid types are: text, markdown, link, actionCard, feedCard.
        msgtype: link
        # Message content in JSON type
        content: ${{format('{{"title":"{0}", "text":"{1}", "messageUrl":"{2}"}}', github.event.pull_request.title, github.event.pull_request.body, github.event.pull_request.url)}}
